# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SE_JYP\Desktop\도서추천시스템\PyQt_UI\로그인화면\전체순위.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -20, 1031, 80))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/맨위 상태창.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(0, 60, 1071, 791))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/북차배경.png")))
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 0, 71, 91))
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/북차 마크3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.ID = QtGui.QLabel(self.centralwidget)
        self.ID.setGeometry(QtCore.QRect(940, 6, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        self.ID.setFont(font)
        self.ID.setAlignment(QtCore.Qt.AlignCenter)
        self.ID.setObjectName(_fromUtf8("ID"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 1, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 8, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/추천도서.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 8, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/도서체크.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 8, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/내가읽은도서.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 1031, 31))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("상태창2.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 60, 861, 21))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/라인.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 730, 861, 21))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/라인.png")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 80, 161, 261))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/국가.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 270, 161, 421))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/장르.png")))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Korean = QtGui.QPushButton(self.centralwidget)
        self.Korean.setGeometry(QtCore.QRect(13, 140, 131, 41))
        self.Korean.setText(_fromUtf8(""))
        self.Korean.setDefault(False)
        self.Korean.setFlat(True)
        self.Korean.setObjectName(_fromUtf8("Korean"))
        self.English = QtGui.QPushButton(self.centralwidget)
        self.English.setGeometry(QtCore.QRect(13, 186, 131, 41))
        self.English.setText(_fromUtf8(""))
        self.English.setFlat(True)
        self.English.setObjectName(_fromUtf8("English"))
        self.Japan = QtGui.QPushButton(self.centralwidget)
        self.Japan.setGeometry(QtCore.QRect(13, 234, 131, 41))
        self.Japan.setText(_fromUtf8(""))
        self.Japan.setFlat(True)
        self.Japan.setObjectName(_fromUtf8("Japan"))
        self.AllNation = QtGui.QPushButton(self.centralwidget)
        self.AllNation.setGeometry(QtCore.QRect(17, 92, 131, 41))
        self.AllNation.setText(_fromUtf8(""))
        self.AllNation.setFlat(True)
        self.AllNation.setObjectName(_fromUtf8("AllNation"))
        self.AllGenre = QtGui.QPushButton(self.centralwidget)
        self.AllGenre.setGeometry(QtCore.QRect(10, 290, 141, 41))
        self.AllGenre.setText(_fromUtf8(""))
        self.AllGenre.setFlat(True)
        self.AllGenre.setObjectName(_fromUtf8("AllGenre"))
        self.Thriller = QtGui.QPushButton(self.centralwidget)
        self.Thriller.setGeometry(QtCore.QRect(10, 340, 141, 41))
        self.Thriller.setText(_fromUtf8(""))
        self.Thriller.setFlat(True)
        self.Thriller.setObjectName(_fromUtf8("Thriller"))
        self.Romance = QtGui.QPushButton(self.centralwidget)
        self.Romance.setGeometry(QtCore.QRect(10, 390, 141, 41))
        self.Romance.setText(_fromUtf8(""))
        self.Romance.setFlat(True)
        self.Romance.setObjectName(_fromUtf8("Romance"))
        self.SF = QtGui.QPushButton(self.centralwidget)
        self.SF.setGeometry(QtCore.QRect(10, 435, 141, 41))
        self.SF.setText(_fromUtf8(""))
        self.SF.setFlat(True)
        self.SF.setObjectName(_fromUtf8("SF"))
        self.Family = QtGui.QPushButton(self.centralwidget)
        self.Family.setGeometry(QtCore.QRect(10, 484, 141, 41))
        self.Family.setText(_fromUtf8(""))
        self.Family.setFlat(True)
        self.Family.setObjectName(_fromUtf8("Family"))
        self.Book1 = QtGui.QPushButton(self.centralwidget)
        self.Book1.setGeometry(QtCore.QRect(160, 80, 130, 190))
        self.Book1.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Book/x9791130605210.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Book1.setIcon(icon4)
        self.Book1.setIconSize(QtCore.QSize(180, 180))
        self.Book1.setObjectName(_fromUtf8("Book1"))
        self.Book1Name = QtGui.QLabel(self.centralwidget)
        self.Book1Name.setGeometry(QtCore.QRect(160, 280, 131, 16))
        self.Book1Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book1Name.setObjectName(_fromUtf8("Book1Name"))
        self.Book3 = QtGui.QPushButton(self.centralwidget)
        self.Book3.setGeometry(QtCore.QRect(420, 80, 130, 190))
        self.Book3.setObjectName(_fromUtf8("Book3"))
        self.Book2 = QtGui.QPushButton(self.centralwidget)
        self.Book2.setGeometry(QtCore.QRect(290, 80, 130, 190))
        self.Book2.setObjectName(_fromUtf8("Book2"))
        self.Book4 = QtGui.QPushButton(self.centralwidget)
        self.Book4.setGeometry(QtCore.QRect(160, 300, 130, 190))
        self.Book4.setObjectName(_fromUtf8("Book4"))
        self.Book5 = QtGui.QPushButton(self.centralwidget)
        self.Book5.setGeometry(QtCore.QRect(290, 300, 130, 190))
        self.Book5.setObjectName(_fromUtf8("Book5"))
        self.Book6 = QtGui.QPushButton(self.centralwidget)
        self.Book6.setGeometry(QtCore.QRect(420, 300, 130, 190))
        self.Book6.setObjectName(_fromUtf8("Book6"))
        self.Book7 = QtGui.QPushButton(self.centralwidget)
        self.Book7.setGeometry(QtCore.QRect(160, 520, 130, 190))
        self.Book7.setObjectName(_fromUtf8("Book7"))
        self.Book8 = QtGui.QPushButton(self.centralwidget)
        self.Book8.setGeometry(QtCore.QRect(290, 520, 130, 190))
        self.Book8.setObjectName(_fromUtf8("Book8"))
        self.Book9 = QtGui.QPushButton(self.centralwidget)
        self.Book9.setGeometry(QtCore.QRect(420, 520, 130, 190))
        self.Book9.setObjectName(_fromUtf8("Book9"))
        self.Book2Name = QtGui.QLabel(self.centralwidget)
        self.Book2Name.setGeometry(QtCore.QRect(290, 280, 131, 16))
        self.Book2Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book2Name.setObjectName(_fromUtf8("Book2Name"))
        self.Book3Name = QtGui.QLabel(self.centralwidget)
        self.Book3Name.setGeometry(QtCore.QRect(420, 280, 131, 16))
        self.Book3Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book3Name.setObjectName(_fromUtf8("Book3Name"))
        self.Book4Name = QtGui.QLabel(self.centralwidget)
        self.Book4Name.setGeometry(QtCore.QRect(160, 500, 131, 16))
        self.Book4Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book4Name.setObjectName(_fromUtf8("Book4Name"))
        self.Book5Name = QtGui.QLabel(self.centralwidget)
        self.Book5Name.setGeometry(QtCore.QRect(290, 500, 131, 16))
        self.Book5Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book5Name.setObjectName(_fromUtf8("Book5Name"))
        self.Book6Name = QtGui.QLabel(self.centralwidget)
        self.Book6Name.setGeometry(QtCore.QRect(420, 500, 131, 16))
        self.Book6Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book6Name.setObjectName(_fromUtf8("Book6Name"))
        self.Book7Name = QtGui.QLabel(self.centralwidget)
        self.Book7Name.setGeometry(QtCore.QRect(160, 720, 131, 16))
        self.Book7Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book7Name.setObjectName(_fromUtf8("Book7Name"))
        self.Book8Name = QtGui.QLabel(self.centralwidget)
        self.Book8Name.setGeometry(QtCore.QRect(290, 720, 131, 16))
        self.Book8Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book8Name.setObjectName(_fromUtf8("Book8Name"))
        self.Book9Name = QtGui.QLabel(self.centralwidget)
        self.Book9Name.setGeometry(QtCore.QRect(420, 720, 131, 16))
        self.Book9Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Book9Name.setObjectName(_fromUtf8("Book9Name"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(570, 74, 461, 665))
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/책내용2.png")))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.BookName = QtGui.QLabel(self.centralwidget)
        self.BookName.setGeometry(QtCore.QRect(600, 100, 401, 31))
        self.BookName.setObjectName(_fromUtf8("BookName"))
        self.mainBook = QtGui.QPushButton(self.centralwidget)
        self.mainBook.setGeometry(QtCore.QRect(590, 150, 101, 161))
        self.mainBook.setIconSize(QtCore.QSize(180, 180))
        self.mainBook.setObjectName(_fromUtf8("mainBook"))
        self.Genre = QtGui.QLabel(self.centralwidget)
        self.Genre.setGeometry(QtCore.QRect(850, 193, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Genre.setFont(font)
        self.Genre.setObjectName(_fromUtf8("Genre"))
        self.Nation = QtGui.QLabel(self.centralwidget)
        self.Nation.setGeometry(QtCore.QRect(940, 193, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Nation.setFont(font)
        self.Nation.setObjectName(_fromUtf8("Nation"))
        self.ISBN = QtGui.QLabel(self.centralwidget)
        self.ISBN.setGeometry(QtCore.QRect(730, 191, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ISBN.setFont(font)
        self.ISBN.setObjectName(_fromUtf8("ISBN"))
        self.Recommend = QtGui.QPushButton(self.centralwidget)
        self.Recommend.setGeometry(QtCore.QRect(700, 250, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Recommend.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/하트.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Recommend.setIcon(icon5)
        self.Recommend.setIconSize(QtCore.QSize(30, 30))
        self.Recommend.setFlat(True)
        self.Recommend.setObjectName(_fromUtf8("Recommend"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(600, 362, 56, 20))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(552, 79, 20, 651))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        self.RecommendCount = QtGui.QPushButton(self.centralwidget)
        self.RecommendCount.setGeometry(QtCore.QRect(790, 240, 91, 51))
        self.RecommendCount.setText(_fromUtf8(""))
        self.RecommendCount.setIconSize(QtCore.QSize(30, 30))
        self.RecommendCount.setFlat(True)
        self.RecommendCount.setObjectName(_fromUtf8("RecommendCount"))
        self.Genre_2 = QtGui.QLabel(self.centralwidget)
        self.Genre_2.setGeometry(QtCore.QRect(820, 212, 91, 16))
        self.Genre_2.setText(_fromUtf8(""))
        self.Genre_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Genre_2.setObjectName(_fromUtf8("Genre_2"))
        self.Nation_2 = QtGui.QLabel(self.centralwidget)
        self.Nation_2.setGeometry(QtCore.QRect(920, 212, 71, 16))
        self.Nation_2.setText(_fromUtf8(""))
        self.Nation_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Nation_2.setObjectName(_fromUtf8("Nation_2"))
        self.ISBN_2 = QtGui.QLabel(self.centralwidget)
        self.ISBN_2.setGeometry(QtCore.QRect(692, 212, 121, 16))
        self.ISBN_2.setText(_fromUtf8(""))
        self.ISBN_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ISBN_2.setObjectName(_fromUtf8("ISBN_2"))
        self.BookInfo = QtGui.QTextEdit(self.centralwidget)
        self.BookInfo.setEnabled(False)
        self.BookInfo.setGeometry(QtCore.QRect(600, 390, 411, 331))
        self.BookInfo.setObjectName(_fromUtf8("BookInfo"))
        self.Author = QtGui.QLabel(self.centralwidget)
        self.Author.setGeometry(QtCore.QRect(696, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Author.setFont(font)
        self.Author.setObjectName(_fromUtf8("Author"))
        self.Author_2 = QtGui.QLabel(self.centralwidget)
        self.Author_2.setGeometry(QtCore.QRect(784, 169, 211, 20))
        self.Author_2.setText(_fromUtf8(""))
        self.Author_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Author_2.setObjectName(_fromUtf8("Author_2"))
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.ID.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.Korean.raise_()
        self.English.raise_()
        self.Japan.raise_()
        self.AllNation.raise_()
        self.AllGenre.raise_()
        self.Thriller.raise_()
        self.Romance.raise_()
        self.SF.raise_()
        self.Family.raise_()
        self.Book1.raise_()
        self.Book1Name.raise_()
        self.Book3.raise_()
        self.Book2.raise_()
        self.Book4.raise_()
        self.Book5.raise_()
        self.Book6.raise_()
        self.Book7.raise_()
        self.Book8.raise_()
        self.Book9.raise_()
        self.Book2Name.raise_()
        self.Book3Name.raise_()
        self.Book4Name.raise_()
        self.Book5Name.raise_()
        self.Book6Name.raise_()
        self.Book7Name.raise_()
        self.Book8Name.raise_()
        self.Book9Name.raise_()
        self.label_19.raise_()
        self.BookName.raise_()
        self.mainBook.raise_()
        self.Genre.raise_()
        self.Nation.raise_()
        self.ISBN.raise_()
        self.Recommend.raise_()
        self.label_25.raise_()
        self.verticalScrollBar.raise_()
        self.RecommendCount.raise_()
        self.Genre_2.raise_()
        self.Nation_2.raise_()
        self.ISBN_2.raise_()
        self.BookInfo.raise_()
        self.Author.raise_()
        self.Author_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.ID.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#3a3a3a;\">회원ID</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#242424;\">전체순위</span></p></body></html>", None))
        self.pushButton_2.setText(_translate("MainWindow", "맞춤추천", None))
        self.pushButton_3.setText(_translate("MainWindow", "도서체크", None))
        self.pushButton_4.setText(_translate("MainWindow", "내가읽은도서", None))
        self.Book1Name.setText(_translate("MainWindow", "TextLabel", None))
        self.Book3.setText(_translate("MainWindow", "PushButton", None))
        self.Book2.setText(_translate("MainWindow", "PushButton", None))
        self.Book4.setText(_translate("MainWindow", "PushButton", None))
        self.Book5.setText(_translate("MainWindow", "PushButton", None))
        self.Book6.setText(_translate("MainWindow", "PushButton", None))
        self.Book7.setText(_translate("MainWindow", "PushButton", None))
        self.Book8.setText(_translate("MainWindow", "PushButton", None))
        self.Book9.setText(_translate("MainWindow", "PushButton", None))
        self.Book2Name.setText(_translate("MainWindow", "TextLabel", None))
        self.Book3Name.setText(_translate("MainWindow", "TextLabel", None))
        self.Book4Name.setText(_translate("MainWindow", "TextLabel", None))
        self.Book5Name.setText(_translate("MainWindow", "TextLabel", None))
        self.Book6Name.setText(_translate("MainWindow", "TextLabel", None))
        self.Book7Name.setText(_translate("MainWindow", "TextLabel", None))
        self.Book8Name.setText(_translate("MainWindow", "TextLabel", None))
        self.Book9Name.setText(_translate("MainWindow", "TextLabel", None))
        self.BookName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">책제목</span></p></body></html>", None))
        self.mainBook.setText(_translate("MainWindow", "image", None))
        self.Genre.setText(_translate("MainWindow", "장르", None))
        self.Nation.setText(_translate("MainWindow", "국적", None))
        self.ISBN.setText(_translate("MainWindow", "ISBN", None))
        self.Recommend.setText(_translate("MainWindow", "추천수 :", None))
        self.label_25.setText(_translate("MainWindow", "책소개", None))
        self.BookInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.Author.setText(_translate("MainWindow", "저자이름 :", None))

import recommend_rc
