# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SE_JYP\Desktop\도서추천시스템\PyQt_UI\로그인화면\도서체크.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -20, 1031, 80))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/맨위 상태창.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(-10, 60, 1071, 791))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/북차배경.png")))
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 0, 71, 91))
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/북차 마크3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.ID = QtGui.QLabel(self.centralwidget)
        self.ID.setGeometry(QtCore.QRect(940, 7, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        self.ID.setFont(font)
        self.ID.setAlignment(QtCore.Qt.AlignCenter)
        self.ID.setObjectName(_fromUtf8("ID"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 2, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 7, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/추천도서.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 7, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/도서체크.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 7, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI/내가읽은도서.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 1031, 31))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("상태창2.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 60, 861, 21))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/라인.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 730, 861, 21))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/라인.png")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 80, 161, 261))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/국가.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 270, 161, 421))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/UI/장르.png")))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Korea = QtGui.QPushButton(self.centralwidget)
        self.Korea.setGeometry(QtCore.QRect(20, 138, 121, 41))
        self.Korea.setText(_fromUtf8(""))
        self.Korea.setDefault(False)
        self.Korea.setFlat(True)
        self.Korea.setObjectName(_fromUtf8("Korea"))
        self.English = QtGui.QPushButton(self.centralwidget)
        self.English.setGeometry(QtCore.QRect(20, 188, 121, 41))
        self.English.setText(_fromUtf8(""))
        self.English.setFlat(True)
        self.English.setObjectName(_fromUtf8("English"))
        self.Japan = QtGui.QPushButton(self.centralwidget)
        self.Japan.setGeometry(QtCore.QRect(20, 236, 121, 41))
        self.Japan.setText(_fromUtf8(""))
        self.Japan.setFlat(True)
        self.Japan.setObjectName(_fromUtf8("Japan"))
        self.AllNation = QtGui.QPushButton(self.centralwidget)
        self.AllNation.setGeometry(QtCore.QRect(18, 93, 121, 41))
        self.AllNation.setText(_fromUtf8(""))
        self.AllNation.setFlat(True)
        self.AllNation.setObjectName(_fromUtf8("AllNation"))
        self.AllGenre = QtGui.QPushButton(self.centralwidget)
        self.AllGenre.setGeometry(QtCore.QRect(20, 290, 121, 41))
        self.AllGenre.setText(_fromUtf8(""))
        self.AllGenre.setFlat(True)
        self.AllGenre.setObjectName(_fromUtf8("AllGenre"))
        self.Thriller = QtGui.QPushButton(self.centralwidget)
        self.Thriller.setGeometry(QtCore.QRect(20, 340, 121, 41))
        self.Thriller.setText(_fromUtf8(""))
        self.Thriller.setFlat(True)
        self.Thriller.setObjectName(_fromUtf8("Thriller"))
        self.Romance = QtGui.QPushButton(self.centralwidget)
        self.Romance.setGeometry(QtCore.QRect(20, 388, 121, 41))
        self.Romance.setText(_fromUtf8(""))
        self.Romance.setFlat(True)
        self.Romance.setObjectName(_fromUtf8("Romance"))
        self.SF = QtGui.QPushButton(self.centralwidget)
        self.SF.setGeometry(QtCore.QRect(20, 434, 121, 41))
        self.SF.setText(_fromUtf8(""))
        self.SF.setFlat(True)
        self.SF.setObjectName(_fromUtf8("SF"))
        self.Family = QtGui.QPushButton(self.centralwidget)
        self.Family.setGeometry(QtCore.QRect(20, 483, 111, 41))
        self.Family.setText(_fromUtf8(""))
        self.Family.setFlat(True)
        self.Family.setObjectName(_fromUtf8("Family"))
        self.Book1 = QtGui.QPushButton(self.centralwidget)
        self.Book1.setGeometry(QtCore.QRect(160, 80, 130, 190))
        self.Book1.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Book/x9788970638621.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Book1.setIcon(icon4)
        self.Book1.setIconSize(QtCore.QSize(180, 180))
        self.Book1.setObjectName(_fromUtf8("Book1"))
        self.Book3 = QtGui.QPushButton(self.centralwidget)
        self.Book3.setGeometry(QtCore.QRect(440, 80, 130, 190))
        self.Book3.setText(_fromUtf8(""))
        self.Book3.setObjectName(_fromUtf8("Book3"))
        self.Book2 = QtGui.QPushButton(self.centralwidget)
        self.Book2.setGeometry(QtCore.QRect(300, 80, 130, 190))
        self.Book2.setText(_fromUtf8(""))
        self.Book2.setObjectName(_fromUtf8("Book2"))
        self.Book7 = QtGui.QPushButton(self.centralwidget)
        self.Book7.setGeometry(QtCore.QRect(160, 300, 130, 190))
        self.Book7.setText(_fromUtf8(""))
        self.Book7.setObjectName(_fromUtf8("Book7"))
        self.Book9 = QtGui.QPushButton(self.centralwidget)
        self.Book9.setGeometry(QtCore.QRect(440, 300, 130, 190))
        self.Book9.setText(_fromUtf8(""))
        self.Book9.setObjectName(_fromUtf8("Book9"))
        self.Book10 = QtGui.QPushButton(self.centralwidget)
        self.Book10.setGeometry(QtCore.QRect(580, 300, 130, 190))
        self.Book10.setText(_fromUtf8(""))
        self.Book10.setObjectName(_fromUtf8("Book10"))
        self.Book13 = QtGui.QPushButton(self.centralwidget)
        self.Book13.setGeometry(QtCore.QRect(160, 520, 130, 190))
        self.Book13.setText(_fromUtf8(""))
        self.Book13.setObjectName(_fromUtf8("Book13"))
        self.Book14 = QtGui.QPushButton(self.centralwidget)
        self.Book14.setGeometry(QtCore.QRect(300, 520, 130, 190))
        self.Book14.setText(_fromUtf8(""))
        self.Book14.setObjectName(_fromUtf8("Book14"))
        self.Book15 = QtGui.QPushButton(self.centralwidget)
        self.Book15.setGeometry(QtCore.QRect(440, 520, 130, 190))
        self.Book15.setText(_fromUtf8(""))
        self.Book15.setObjectName(_fromUtf8("Book15"))
        self.Book6 = QtGui.QPushButton(self.centralwidget)
        self.Book6.setGeometry(QtCore.QRect(860, 80, 130, 190))
        self.Book6.setText(_fromUtf8(""))
        self.Book6.setObjectName(_fromUtf8("Book6"))
        self.Book4 = QtGui.QPushButton(self.centralwidget)
        self.Book4.setGeometry(QtCore.QRect(580, 80, 130, 190))
        self.Book4.setText(_fromUtf8(""))
        self.Book4.setObjectName(_fromUtf8("Book4"))
        self.Book5 = QtGui.QPushButton(self.centralwidget)
        self.Book5.setGeometry(QtCore.QRect(720, 80, 130, 190))
        self.Book5.setText(_fromUtf8(""))
        self.Book5.setObjectName(_fromUtf8("Book5"))
        self.Book11 = QtGui.QPushButton(self.centralwidget)
        self.Book11.setGeometry(QtCore.QRect(720, 300, 130, 190))
        self.Book11.setText(_fromUtf8(""))
        self.Book11.setObjectName(_fromUtf8("Book11"))
        self.Book8 = QtGui.QPushButton(self.centralwidget)
        self.Book8.setGeometry(QtCore.QRect(300, 300, 130, 190))
        self.Book8.setText(_fromUtf8(""))
        self.Book8.setObjectName(_fromUtf8("Book8"))
        self.Book12 = QtGui.QPushButton(self.centralwidget)
        self.Book12.setGeometry(QtCore.QRect(860, 300, 130, 190))
        self.Book12.setText(_fromUtf8(""))
        self.Book12.setObjectName(_fromUtf8("Book12"))
        self.Book16 = QtGui.QPushButton(self.centralwidget)
        self.Book16.setGeometry(QtCore.QRect(580, 520, 130, 190))
        self.Book16.setText(_fromUtf8(""))
        self.Book16.setObjectName(_fromUtf8("Book16"))
        self.Book17 = QtGui.QPushButton(self.centralwidget)
        self.Book17.setGeometry(QtCore.QRect(720, 520, 130, 190))
        self.Book17.setText(_fromUtf8(""))
        self.Book17.setObjectName(_fromUtf8("Book17"))
        self.Book18 = QtGui.QPushButton(self.centralwidget)
        self.Book18.setGeometry(QtCore.QRect(860, 520, 130, 190))
        self.Book18.setText(_fromUtf8(""))
        self.Book18.setObjectName(_fromUtf8("Book18"))
        self.BookCheck1 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck1.setGeometry(QtCore.QRect(161, 280, 131, 16))
        self.BookCheck1.setObjectName(_fromUtf8("BookCheck1"))
        self.BookCheck2 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck2.setGeometry(QtCore.QRect(300, 280, 131, 16))
        self.BookCheck2.setObjectName(_fromUtf8("BookCheck2"))
        self.BookCheck3 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck3.setGeometry(QtCore.QRect(441, 280, 131, 16))
        self.BookCheck3.setObjectName(_fromUtf8("BookCheck3"))
        self.BookCheck4 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck4.setGeometry(QtCore.QRect(581, 280, 131, 16))
        self.BookCheck4.setObjectName(_fromUtf8("BookCheck4"))
        self.BookCheck5 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck5.setGeometry(QtCore.QRect(723, 280, 131, 16))
        self.BookCheck5.setObjectName(_fromUtf8("BookCheck5"))
        self.BookCheck6 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck6.setGeometry(QtCore.QRect(862, 280, 131, 16))
        self.BookCheck6.setObjectName(_fromUtf8("BookCheck6"))
        self.BookCheck7 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck7.setGeometry(QtCore.QRect(161, 500, 131, 16))
        self.BookCheck7.setObjectName(_fromUtf8("BookCheck7"))
        self.BookCheck8 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck8.setGeometry(QtCore.QRect(300, 500, 131, 16))
        self.BookCheck8.setObjectName(_fromUtf8("BookCheck8"))
        self.BookCheck9 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck9.setGeometry(QtCore.QRect(440, 500, 131, 16))
        self.BookCheck9.setObjectName(_fromUtf8("BookCheck9"))
        self.BookCheck10 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck10.setGeometry(QtCore.QRect(580, 500, 131, 16))
        self.BookCheck10.setObjectName(_fromUtf8("BookCheck10"))
        self.BookCheck11 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck11.setGeometry(QtCore.QRect(720, 500, 131, 16))
        self.BookCheck11.setObjectName(_fromUtf8("BookCheck11"))
        self.BookCheck12 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck12.setGeometry(QtCore.QRect(860, 500, 131, 16))
        self.BookCheck12.setObjectName(_fromUtf8("BookCheck12"))
        self.BookCheck13 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck13.setGeometry(QtCore.QRect(160, 720, 131, 16))
        self.BookCheck13.setObjectName(_fromUtf8("BookCheck13"))
        self.BookCheck14 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck14.setGeometry(QtCore.QRect(300, 720, 131, 16))
        self.BookCheck14.setObjectName(_fromUtf8("BookCheck14"))
        self.BookCheck15 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck15.setGeometry(QtCore.QRect(440, 720, 131, 16))
        self.BookCheck15.setObjectName(_fromUtf8("BookCheck15"))
        self.BookCheck16 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck16.setGeometry(QtCore.QRect(580, 720, 131, 16))
        self.BookCheck16.setObjectName(_fromUtf8("BookCheck16"))
        self.BookCheck17 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck17.setGeometry(QtCore.QRect(720, 720, 131, 16))
        self.BookCheck17.setObjectName(_fromUtf8("BookCheck17"))
        self.BookCheck18 = QtGui.QCheckBox(self.centralwidget)
        self.BookCheck18.setGeometry(QtCore.QRect(860, 720, 131, 16))
        self.BookCheck18.setObjectName(_fromUtf8("BookCheck18"))
        self.verticalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(995, 80, 16, 661))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.ID.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.Korea.raise_()
        self.English.raise_()
        self.Japan.raise_()
        self.AllNation.raise_()
        self.AllGenre.raise_()
        self.Thriller.raise_()
        self.Romance.raise_()
        self.SF.raise_()
        self.Family.raise_()
        self.Book1.raise_()
        self.Book3.raise_()
        self.Book2.raise_()
        self.Book7.raise_()
        self.Book9.raise_()
        self.Book10.raise_()
        self.Book13.raise_()
        self.Book14.raise_()
        self.Book15.raise_()
        self.Book6.raise_()
        self.Book4.raise_()
        self.Book5.raise_()
        self.Book11.raise_()
        self.Book8.raise_()
        self.Book12.raise_()
        self.Book16.raise_()
        self.Book17.raise_()
        self.Book18.raise_()
        self.BookCheck1.raise_()
        self.BookCheck2.raise_()
        self.BookCheck3.raise_()
        self.BookCheck4.raise_()
        self.BookCheck5.raise_()
        self.BookCheck6.raise_()
        self.BookCheck7.raise_()
        self.BookCheck8.raise_()
        self.BookCheck9.raise_()
        self.BookCheck10.raise_()
        self.BookCheck11.raise_()
        self.BookCheck12.raise_()
        self.BookCheck13.raise_()
        self.BookCheck14.raise_()
        self.BookCheck15.raise_()
        self.BookCheck16.raise_()
        self.BookCheck17.raise_()
        self.BookCheck18.raise_()
        self.verticalScrollBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.ID.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#3a3a3a;\">회원ID</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#242424;\">도서체크</span></p></body></html>", None))
        self.pushButton_2.setText(_translate("MainWindow", "맞춤추천", None))
        self.pushButton_3.setText(_translate("MainWindow", "도서체크", None))
        self.pushButton_4.setText(_translate("MainWindow", "내가읽은도서", None))
        self.BookCheck1.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck2.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck3.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck4.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck5.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck6.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck7.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck8.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck9.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck10.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck11.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck12.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck13.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck14.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck15.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck16.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck17.setText(_translate("MainWindow", "읽은 책표시", None))
        self.BookCheck18.setText(_translate("MainWindow", "읽은 책표시", None))

import recommend_rc
