# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SE_JYP\Desktop\도서추천시스템\PyQt_UI\로그인화면\로그인 화면1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1031, 31))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/img/맨위 상태창.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 1031, 21))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/img/상태창2.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(0, 50, 1071, 791))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/img/북차배경.png")))
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 60, 221, 311))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/img/북차 마크 작은거.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 336, 260, 291))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/img/로그인 배경.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(375, 340, 251, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setTextFormat(QtCore.Qt.LogText)
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/img/로그인 배경1.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(475, 350, 61, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(375, 390, 251, 231))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/img/로그인 배경2.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(387, 500, 230, 71))
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/로그인버튼.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(240, 70))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(458, 570, 91, 31))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/회원가입.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(100, 16))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.textEdit = QtGui.QLineEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(387, 407, 230, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textEdit.setFrame(True)
        self.textEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.textEdit.setDragEnabled(True)
        self.textEdit.setReadOnly(False)
        self.textEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.textEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(387, 457, 230, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textEdit_2.setEchoMode(QtGui.QLineEdit.Normal)
        self.textEdit_2.setDragEnabled(True)
        self.textEdit_2.setReadOnly(False)
        self.textEdit_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.warning = QtGui.QLabel(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(360, 150, 291, 151))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.warning.setFont(font)
        self.warning.setText(_fromUtf8(""))
        self.warning.setAlignment(QtCore.Qt.AlignCenter)
        self.warning.setObjectName(_fromUtf8("warning"))
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.warning.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.textEdit, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), self.clear1)
        QtCore.QObject.connect(self.textEdit_2, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), self.clear2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def clear1(self):
        self.warning.clear()
        self.textEdit.clear()
    def clear2(self):
        self.textEdit_2.setEchoMode(QtGui.QLineEdit.Password)
        self.textEdit_2.clear()

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'맑은 고딕\';font-size:12pt; font-weight:600; color:#515151;\">로그인</span></p></body></html>", None))
        self.textEdit.setText(_translate("MainWindow", "아이디", None))
        self.textEdit_2.setText(_translate("MainWindow", "비밀번호", None))

import login_rc
