# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SE_JYP\Desktop\도서추천시스템\PyQt_UI\로그인화면\회원가입 화면1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1031, 31))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/맨위 상태창.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 28, 1031, 31))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/상태창2.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(-10, 60, 1071, 791))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/북차배경.png")))
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 60, 221, 311))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/북차 마크 작은거.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 336, 260, 411))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/로그인 배경.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(375, 340, 251, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setTextFormat(QtCore.Qt.LogText)
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/로그인 배경1.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(464, 350, 101, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(375, 390, 251, 351))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/로그인 배경2.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(390, 587, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dateEdit.setWrapping(False)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dateEdit.setSpecialValueText(_fromUtf8(""))
        self.dateEdit.setDate(QtCore.QDate(1993, 3, 14))
        self.dateEdit.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.dateEdit_2 = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(465, 587, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dateEdit_2.setWrapping(False)
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dateEdit_2.setSpecialValueText(_fromUtf8(""))
        self.dateEdit_2.setDate(QtCore.QDate(1993, 3, 14))
        self.dateEdit_2.setCurrentSection(QtGui.QDateTimeEdit.MonthSection)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.dateEdit_3 = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit_3.setGeometry(QtCore.QRect(540, 587, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dateEdit_3.setFont(font)
        self.dateEdit_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dateEdit_3.setWrapping(False)
        self.dateEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_3.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dateEdit_3.setSpecialValueText(_fromUtf8(""))
        self.dateEdit_3.setDate(QtCore.QDate(1993, 3, 14))
        self.dateEdit_3.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.dateEdit_3.setObjectName(_fromUtf8("dateEdit_3"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(506, 621, 102, 46))
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/여.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(394, 621, 102, 46))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/남.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 670, 230, 61))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_3.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/SignUp/등록하기.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(210, 120))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.textEdit = QtGui.QLineEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(385, 404, 230, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.textEdit.setDragEnabled(True)
        self.textEdit.setReadOnly(False)
        self.textEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.textEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(385, 450, 230, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textEdit_2.setEchoMode(QtGui.QLineEdit.Normal)
        self.textEdit_2.setDragEnabled(True)
        self.textEdit_2.setReadOnly(False)
        self.textEdit_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.textEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(386, 495, 230, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textEdit_4.setFrame(True)
        self.textEdit_4.setEchoMode(QtGui.QLineEdit.Normal)
        self.textEdit_4.setDragEnabled(True)
        self.textEdit_4.setReadOnly(False)
        self.textEdit_4.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.textEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(387, 541, 230, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textEdit_3.setEchoMode(QtGui.QLineEdit.Normal)
        self.textEdit_3.setDragEnabled(True)
        self.textEdit_3.setReadOnly(False)
        self.textEdit_3.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.warning = QtGui.QLabel(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(360, 140, 291, 151))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.warning.setFont(font)
        self.warning.setText(_fromUtf8(""))
        self.warning.setAlignment(QtCore.Qt.AlignCenter)
        self.warning.setObjectName(_fromUtf8("warning"))
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.warning.raise_()
        self.textEdit_4.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.dateEdit.raise_()
        self.dateEdit_2.raise_()
        self.dateEdit_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.textEdit, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), self.clear1)
        QtCore.QObject.connect(self.textEdit_2, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), self.clear2)
        QtCore.QObject.connect(self.textEdit_4, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), self.clear3)
        QtCore.QObject.connect(self.textEdit_3, QtCore.SIGNAL(_fromUtf8("selectionChanged()")), self.clear4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def clear1(self):
        self.warning.clear()
        self.textEdit.clear()
    def clear2(self):
        self.warning.clear()
        self.textEdit_2.setEchoMode(QtGui.QLineEdit.Password)
        self.textEdit_2.clear()
    def clear3(self):
        self.warning.clear()
        self.textEdit_4.setEchoMode(QtGui.QLineEdit.Password)
        self.textEdit_4.clear()
    def clear4(self):
        self.warning.clear()
        self.textEdit_3.clear()

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'맑은 고딕\';font-size:12pt; font-weight:600; color:#515151;\">회원가입</span></p></body></html>", None))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy", None))
        self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "MM", None))
        self.dateEdit_3.setDisplayFormat(_translate("MainWindow", "dd", None))
        self.textEdit.setText(_translate("MainWindow", "아이디", None))
        self.textEdit_2.setText(_translate("MainWindow", "비밀번호", None))
        self.textEdit_4.setText(_translate("MainWindow", "비밀번호확인", None))
        self.textEdit_3.setText(_translate("MainWindow", "이름", None))

import SignUp_rc
